"""empty message

Revision ID: 43766ad3bf48
Revises: bf02a23ef3aa
Create Date: 2018-12-11 18:57:19.012704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43766ad3bf48'
down_revision = 'bf02a23ef3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'creator',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'creator',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
