"""empty message

Revision ID: 47b940e77638
Revises: 3e9593be37c2
Create Date: 2018-12-11 17:47:38.410369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b940e77638'
down_revision = '3e9593be37c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sublists',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sublists')
    # ### end Alembic commands ###
