"""empty message

Revision ID: 656cbbed0e97
Revises: 43766ad3bf48
Create Date: 2018-12-11 19:48:09.174916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656cbbed0e97'
down_revision = '43766ad3bf48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_creator_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('task_creator_fkey', 'task', 'person', ['creator'], ['id'])
    # ### end Alembic commands ###
