"""empty message

Revision ID: a04bd4f38e09
Revises: 47b940e77638
Create Date: 2018-12-11 17:50:07.511632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04bd4f38e09'
down_revision = '47b940e77638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sublists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sublists',
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['list.id'], name='sublists_child_id_fkey'),
    sa.ForeignKeyConstraint(['parent_id'], ['list.id'], name='sublists_parent_id_fkey'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id', name='sublists_pkey')
    )
    # ### end Alembic commands ###
