"""empty message

Revision ID: bf02a23ef3aa
Revises: a04bd4f38e09
Create Date: 2018-12-11 17:50:30.820910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf02a23ef3aa'
down_revision = 'a04bd4f38e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sublists',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sublists')
    # ### end Alembic commands ###
