"""empty message

Revision ID: d04a057250b1
Revises: 656cbbed0e97
Create Date: 2018-12-11 20:07:10.179436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04a057250b1'
down_revision = '656cbbed0e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_table('dependencies',
    sa.Column('parent_task_id', sa.Integer(), nullable=False),
    sa.Column('child_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('parent_task_id', 'child_task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependencies')
    op.drop_table('assigned')
    # ### end Alembic commands ###
